In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline


In [2]:
df =pd.read_csv("https://raw.githubusercontent.com/codebasics/py/master/ML/9_decision_tree/Exercise/titanic.csv")

In [3]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Ticket','Cabin','Embarked'],axis =1,inplace =True )

In [5]:
df.head()

Survived  Pclass     Sex   Age     Fare
0         0       3    male  22.0   7.2500
1         1       1  female  38.0  71.2833
2         1       3  female  26.0   7.9250
3         1       1  female  35.0  53.1000
4         0       3    male  35.0   8.0500

In [6]:
target = df.Survived

In [7]:
feature = df.drop(['Survived'],axis =1)

In [8]:
dummies = pd.get_dummies(feature['Sex'])

In [9]:
dummies.head()

female  male
0       0     1
1       1     0
2       1     0
3       1     0
4       0     1

In [10]:
input = pd.concat([feature,dummies],axis ='columns')

In [11]:
input.head()

Pclass     Sex   Age     Fare  female  male
0       3    male  22.0   7.2500       0     1
1       1  female  38.0  71.2833       1     0
2       3  female  26.0   7.9250       1     0
3       1  female  35.0  53.1000       1     0
4       3    male  35.0   8.0500       0     1

In [12]:
input =input.drop(['Sex'],axis = 1)

In [13]:
input.head()

Pclass   Age     Fare  female  male
0       3  22.0   7.2500       0     1
1       1  38.0  71.2833       1     0
2       3  26.0   7.9250       1     0
3       1  35.0  53.1000       1     0
4       3  35.0   8.0500       0     1

In [14]:
input.isna().sum()

Pclass      0
Age       177
Fare        0
female      0
male        0
dtype: int64

In [15]:
input.shape

(891, 5)

In [16]:
input.Age = input.Age.fillna(input.Age.mean())

In [17]:
input.isna().sum()

Pclass    0
Age       0
Fare      0
female    0
male      0
dtype: int64

In [18]:
from sklearn.model_selection import train_test_split


In [19]:
X_train,X_test,y_train,y_test = train_test_split(input,target,test_size=0.2)

In [20]:
from sklearn.naive_bayes import GaussianNB

In [21]:
model =GaussianNB()
model.fit(X_train,y_train)
model.predict(X_test[:10])

array([0, 1, 0, 1, 0, 0, 1, 0, 1, 0])

In [22]:
model.score(X_test,y_test)

0.7318435754189944

In [23]:
y_test[:10]

392    0
887    1
420    0
564    0
804    1
738    0
772    0
157    0
15     1
210    0
Name: Survived, dtype: int64

In [24]:
model.predict_proba(X_test[:10])

array([[0.99183361, 0.00816639],
       [0.00703452, 0.99296548],
       [0.99201237, 0.00798763],
       [0.0621504 , 0.9378496 ],
       [0.99165808, 0.00834192],
       [0.99201237, 0.00798763],
       [0.02886067, 0.97113933],
       [0.99204954, 0.00795046],
       [0.03006423, 0.96993577],
       [0.9912367 , 0.0087633 ]])

## Exercise 2

In [25]:
df = pd.read_csv("https://raw.githubusercontent.com/codebasics/py/master/ML/14_naive_bayes/spam.csv")

In [26]:
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [27]:
df.shape

(5572, 2)

In [28]:
df.groupby('Category').describe()


Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [29]:
df['spam']= df.Category.apply(lambda x: 1 if x =='spam' else 0)
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [30]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.Message,df.spam)

In [31]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
x_train_count = v.fit_transform(X_train.values)

In [32]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()

In [33]:
model.fit(x_train_count,y_train)

MultinomialNB()

In [34]:
emails = [
    'Hey mohan, can we get together to watch football game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

In [35]:
emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])

In [36]:
X_test_count = v.transform(X_test)
model.score(X_test_count, y_test)

0.9870782483847811

## pipeline

In [41]:
from sklearn.pipeline import Pipeline
clf =Pipeline([
    ('vectorizer',CountVectorizer()),
    ('nb',MultinomialNB())])

In [42]:
clf.fit(X_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [43]:
clf.predict(emails)

array([0, 1])

In [44]:
clf.score(X_test,y_test)

0.9870782483847811